FILE_NAME = 'listings.xlsx'
FILE_MIME_TYPE='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
SHEET_NAME = 'Listings'

CATEGORIES = [
    '#',
    'address',
    'unit',
    'city',
    'prov',
    'postal',
    'listPr',
    'salesStatus',
    'taxes',
    'taxYear',
    'lastStatus',
    'unitType',
    'unitType2',
    'lockerNum',
    'lockerLevel',
    'lockerUnit',
    'floorNum',
    'unitNum',
    'roomCount',
    'bedroomCount',
    'washroomCount',
    'washroomTypes',
    'crossSt',
    'mlsNum',
    'possessionDate',
    'numKitchens',
    'hasBasement',
    'hasFireplace',
    'heatType',
    'approxAge',
    'approxSqFeet',
    'sqftSource',
    'unitDirection',
    'pets',
    'locker',
    'maintenance',
    'airCon',
    'taxesIncl',
    'waterIncl',
    'heatIncl',
    'hydroIncl',
    'cablTvIncl',
    'centralAirCon',
    'buildingInsurIncl',
    'parkingIncl',
    'balconyType',
    'ensuiteLaundry',
    'exterior',
    'garage',
    'parking',
    'parkType',
    'parkSpaces',
    'totalParkSpots',
    'parkSpotNum',
    'parkPerMonth',
    'parkLevel',
    'commonElemIncl',
    'textDescriptions',
    'dateAdded'
]

GOOGLE_SCOPES = 'https://www.googleapis.com/auth/drive.file'
GOOGLE_CLIENT_SECRET_FILE = 'client_secret.json'
GOOGLE_APPLICATION_NAME = 'Treb-Web-Scraper-Drive'
GOOGLE_CREDENTIALS_FILE = GOOGLE_APPLICATION_NAME+'.json'